# Generated by Django 5.2.10 on 2026-03-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_post_options_alter_post_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Bài viết'},
        ),
    ]
