# Generated by Django 5.2.10 on 2026-03-25 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.CharField(default='15/01/2006', max_length=50, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_name',
            field=models.CharField(default='IT24B', max_length=50, verbose_name='Lớp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Sêu', max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Nam', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='Link GitHub'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(default='Âm nhạc, Thể thao, Chơi nhạc cụ...', verbose_name='Sở thích'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(default='Gia Lai', max_length=200, verbose_name='Quê quán'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='major',
            field=models.CharField(default='Công nghệ thông tin', max_length=200, verbose_name='Chuyên ngành'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(default='Đại học Đông Á', max_length=200, verbose_name='Trường học'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên dự án')),
                ('description', models.TextField(verbose_name='Mô tả dự án')),
                ('border_color', models.CharField(choices=[('primary', 'Xanh dương'), ('success', 'Xanh lá'), ('danger', 'Đỏ'), ('warning', 'Vàng'), ('dark', 'Đen')], default='primary', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
