# Generated by Django 5.2.10 on 2026-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_birth_date_userprofile_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên người gửi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='Gia Lai, Việt Nam', max_length=255, verbose_name='Địa chỉ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_contact',
            field=models.EmailField(default='yseu17924@gmail.com', max_length=254, verbose_name='Email liên lạc'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Link Facebook'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0348337534', max_length=15, verbose_name='Số điện thoại'),
        ),
    ]
