# Generated by Django 5.2.10 on 2026-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactmessage_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_year',
            field=models.CharField(default='2024-2028', max_length=20, verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(default='107937', max_length=20, verbose_name='Mã sinh viên'),
        ),
    ]
