# Generated by Django 5.2.10 on 2026-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile_academic_year_userprofile_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_title', models.CharField(default='Chào mừng bạn đến với "Góc Nhỏ Của Sêu"', max_length=200)),
                ('greeting_text_1', models.TextField(default='Nơi mình lưu giữ những điều giản dị nhưng ý nghĩa...')),
                ('greeting_text_2', models.TextField(default='Mình là Sêu - một người đang cố gắng mỗi ngày...')),
                ('col1_title', models.CharField(default='Hành trình học tập', max_length=100)),
                ('col1_icon', models.CharField(default='fa-book-open', max_length=50)),
                ('col1_text', models.TextField(default='Học tập là con đường rèn luyện tư duy...')),
                ('col2_title', models.CharField(default='Giai điệu cuộc sống', max_length=100)),
                ('col2_icon', models.CharField(default='fa-music', max_length=50)),
                ('col2_text', models.TextField(default='Âm nhạc là một phần không thể thiếu...')),
                ('col3_title', models.CharField(default='Đam mê sân cỏ', max_length=100)),
                ('col3_icon', models.CharField(default='fa-futbol', max_length=50)),
                ('col3_text', models.TextField(default='Đá bóng không chỉ là thể thao...')),
                ('footer_text', models.TextField(default='“Góc Nhỏ Của Sêu” sẽ là nơi mình chia sẻ...')),
                ('footer_thanks', models.CharField(default='Cảm ơn bạn đã đến với góc nhỏ của mình', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobbies',
            field=models.TextField(default='Thích nghe nhạc, Chơi thể thao, Chơi guitar và piano, Rất thích hát...', verbose_name='Sở thích'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(default='Xã Ia Băng, Gia Lai', max_length=200, verbose_name='Quê quán'),
        ),
    ]
