# Generated by Django 5.2.10 on 2026-03-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homecontent_alter_userprofile_hobbies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='col1_icon',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='col2_icon',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='col3_icon',
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='col1_text',
            field=models.TextField(default='Học tập là con đường rèn luyện tư duy...', verbose_name='Nội dung Cột 1'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='col1_title',
            field=models.CharField(default='Hành trình học tập', max_length=100, verbose_name='Tiêu đề Cột 1 (Học tập)'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='col2_text',
            field=models.TextField(default='Âm nhạc là một phần không thể thiếu...', verbose_name='Nội dung Cột 2'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='col2_title',
            field=models.CharField(default='Giai điệu cuộc sống', max_length=100, verbose_name='Tiêu đề Cột 2 (Âm nhạc)'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='col3_text',
            field=models.TextField(default='Đá bóng không chỉ là thể thao...', verbose_name='Nội dung Cột 3'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='col3_title',
            field=models.CharField(default='Đam mê sân cỏ', max_length=100, verbose_name='Tiêu đề Cột 3 (Thể thao)'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='footer_text',
            field=models.TextField(default='“Góc Nhỏ Của Sêu” sẽ là nơi mình chia sẻ...', verbose_name='Lời nhắn gửi cuối trang'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='footer_thanks',
            field=models.CharField(default='Cảm ơn bạn đã đến với góc nhỏ của mình', max_length=200, verbose_name='Lời cảm ơn (In đậm)'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='greeting_text_1',
            field=models.TextField(default='Nơi mình lưu giữ những điều giản dị nhưng ý nghĩa...', verbose_name='Đoạn giới thiệu 1'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='greeting_text_2',
            field=models.TextField(default='Mình là Sêu - một người đang cố gắng mỗi ngày...', verbose_name='Đoạn giới thiệu 2'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='greeting_title',
            field=models.CharField(default='Chào mừng bạn đến với "Góc Nhỏ Của Sêu"', max_length=200, verbose_name='Tiêu đề chào mừng'),
        ),
    ]
